# Gateway Auth WASM Plugin - Standard Istio Deployment
# NOTE: This is for standard Istio environments. For OpenShift, use wasmplugin-production.yaml
# Updated to match current working configuration

apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: gateway-auth-wasm-plugin
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  phase: AUTHN
  priority: 1000
  url: oci://registry.tannerjc.net/gateway-auth-wasm-plugin:latest
  pluginConfig:
    auth_service:
      endpoint: "http://kube-auth-proxy.auth-system.svc.cluster.local:8080"
      cluster: "outbound|8080||kube-auth-proxy.auth-system.svc.cluster.local"
      verify_path: "/auth"
      timeout: 5000
      tls:
        verify_cert: false
    global_auth:
      enabled: true
