# Gateway Auth WASM Plugin - Production Deployment
# Simple deployment targeting odh-gateway
# Updated: Uses HTTP-only communication with kube-auth-proxy for 302 OAuth redirects

apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: gateway-auth-wasm-plugin
  namespace: openshift-ingress
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: odh-gateway
  phase: AUTHN
  priority: 1000
  url: oci://registry.tannerjc.net/gateway-auth-wasm-plugin:latest
  pluginConfig:
    auth_service:
      endpoint: "http://kube-auth-proxy.openshift-ingress.svc.cluster.local:8080"
      cluster: "outbound|8080||kube-auth-proxy.openshift-ingress.svc.cluster.local"
      verify_path: "/auth"
      timeout: 5000
      tls:
        verify_cert: false
    global_auth:
      enabled: true
